# Generated by Django 4.2 on 2023-05-03 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='image_url',
            field=models.URLField(default='https://csc648whereweeatinmeow.s3.us-west-2.amazonaws.com/cat-1.png'),
        ),
        migrations.AddField(
            model_name='history',
            name='user_rating',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
